### ISSUE TITLE
建议发布可执行文件

### ISSUE THREAD

**Issue by kekeqy** [numberwolf/FFmpeg-QuQi-H265-FLV-RTMP#2]
建议发布可执行文件，这样直接就可以拿来用，而不用自己去编译。

**Comment by kekeqy** [comment]
win、linux、macos各来一份吧！

**Comment by numberwolf** [comment]
由于编译的定制化需求甚高，同时对于可执行文件的依赖多少需求不同，所以需要自己在机器设备编译即可
