### ISSUE TITLE
你定义的flv常量都没用，你试过可以吗？

### ISSUE THREAD

**Issue by WJZMC** [numberwolf/FFmpeg-QuQi-H265-FLV-RTMP#3]
你定义的flv常量都没用，你试过可以吗？

**Comment by numberwolf** [comment]
测试过可以，你编不出来吗？

**Comment by numberwolf** [comment]
你先编译出来，跑一下。 
这个是主要用途是吧265 codec 喂给 flv box的。（请知晓）

**Comment by WJZMC** [comment]
sorry，我的问题，这个是可以的，我验证完了，我看了网上好几个版本的，你这个是可以的，我理解的有偏差

**Comment by numberwolf** [comment]
> sorry，我的问题，这个是可以的，我验证完了，我看了网上好几个版本的，你这个是可以的，我理解的有偏差

有用的话可以给个star~~~

**Comment by WJZMC** [comment]
已star，哥们你试过cuda吗？PATH="$bin:$PATH" PKG_CONFIG_PATH="$dst/lib:$dst/lib/pkgconfig:/usr/lib64/pkgconfig:$PKG_CONFIG_PATH" ./configure  --prefix="$dst" --pkg-config-flags="--static " --extra-cflags="-I/usr/include/ -I/usr/local/cuda/include/ -I$dst/include"  --extra-ldflags="-L/usr/local/cuda/lib64/ -L/usr/local/cuda/lib64/stubs -L$dst/lib -L/usr/lib64/" --extra-libs=-lpthread --extra-libs=-lm --bindir="$bin" --disable-shared --enable-static --enable-gpl --enable-libfdk_aac  --enable-libmp3lame --enable-libx264  --enable-nonfree  --enable-libopus --enable-libvorbis --enable-libvpx --enable-demuxer=rtsp --enable-muxer=rtsp --enable-hardcoded-tables   --enable-openssl --enable-protocol=rtmp  --enable-libtheora --enable-libx265 --enable-libfontconfig --enable-libfribidi --enable-libfreetype  --enable-librtmp --enable-libass --enable-libnpp --enable-cuda --enable-cuvid --enable-nvenc --extra-ldexeflags="-static"

**Comment by WJZMC** [comment]
--extra-ldexeflags="-static" 加这个后，libnpp报错

**Comment by WJZMC** [comment]
gcc -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -I/usr/include/ -I/usr/local/cuda/include/ -I/root/ffmpeg_build/include -std=c11 -fomit-frame-pointer -I/root/ffmpeg_build/include -pthread -I/root/myffmpeg/ffmpeg_build/include -I/root/ffmpeg_build/include -I/root/ffmpeg_build/include/harfbuzz -I/root/ffmpeg_build/include/fribidi -I/root/ffmpeg_build/include/freetype2 -I/root/ffmpeg_build/include/glib-2.0 -I/root/ffmpeg_build/lib/glib-2.0/include -I/root/myffmpeg/ffmpeg_build/include -I/root/ffmpeg_build/include/libpng16 -I/root/ffmpeg_build/include/libxml2 -I/root/ffmpeg_build/include -I/root/ffmpeg_build/include -I/root/ffmpeg_build/include/libxml2 -I/root/ffmpeg_build/include/freetype2 -I/root/myffmpeg/ffmpeg_build/include -I/root/ffmpeg_build/include/libpng16 -I/root/ffmpeg_build/include/freetype2 -I/root/myffmpeg/ffmpeg_build/include -I/root/ffmpeg_build/include/libpng16 -I/root/ffmpeg_build/include/fribidi -c -o /tmp/ffconf.3QYMBuf4/test.o /tmp/ffconf.3QYMBuf4/test.c
gcc -L/usr/local/cuda/lib64/ -L/usr/local/cuda/lib64/stubs -L/root/ffmpeg_build/lib -L/usr/lib64/ -Wl,--as-needed -Wl,-z,noexecstack -static -o /tmp/ffconf.3QYMBuf4/test /tmp/ffconf.3QYMBuf4/test.o -lnppig -lnppicc -lnppc -lnppidei -lm -lpthread
/usr/local/cuda/lib64//libnppc.a(npp.o): In function `nppInitTls()':
npp.cpp:(.text+0x5): undefined reference to `culibosInit'
npp.cpp:(.text+0xc): undefined reference to `culibosTlsAlloc'
/usr/local/cuda/lib64//libnppc.a(npp.o): In function `nppGetStreamContext':
npp.cpp:(.text+0x83): undefined reference to `cudaGetDevice'
npp.cpp:(.text+0x97): undefined reference to `cudaGetDeviceProperties'
npp.cpp:(.text+0xa6): undefined reference to `cudaStreamGetFlags'
npp.cpp:(.text+0x10d): undefined reference to `cudaDeviceGetAttribute'
npp.cpp:(.text+0x12c): undefined reference to `cudaDeviceGetAttribute'
npp.cpp:(.text+0x258): undefined reference to `cudaGetDevice'
npp.cpp:(.text+0x26c): undefined reference to `cudaGetDeviceProperties'
npp.cpp:(.text+0x27f): undefined reference to `cudaStreamGetFlags'
npp.cpp:(.text+0x2e4): undefined reference to `cudaDeviceGetAttribute'
npp.cpp:(.text+0x303): undefined reference to `cudaDeviceGetAttribute'
/usr/local/cuda/lib64//libnppc.a(npp.o): In function `nppGetStreamNumSMs':
npp.cpp:(.text+0x371): undefined reference to `culibosTlsGetValue'
npp.cpp:(.text+0x39f): undefined reference to `cudaGetDevice'
npp.cpp:(.text+0x3b3): undefined reference to `cudaGetDeviceProperties'
npp.cpp:(.text+0x3c2): undefined reference to `cudaStreamGetFlags'
npp.cpp:(.text+0x42f): undefined reference to `cudaDeviceGetAttribute'
npp.cpp:(.text+0x458): undefined reference to `cudaGetDevice'
npp.cpp:(.text+0x46c): undefined reference to `cudaGetDeviceProperties'
npp.cpp:(.text+0x47f): undefined reference to `cudaStreamGetFlags'
npp.cpp:(.text+0x4e4): undefined reference to `cudaDeviceGetAttribute'
npp.cpp:(.text+0x503): undefined reference to `cudaDeviceGetAttribute'
npp.cpp:(.text+0x553): undefined reference to `cudaDeviceGetAttribute'
/usr/local/cuda/lib64//libnppc.a(npp.o): In function `nppGetStreamMaxThreadsPerSM':
npp.cpp:(.text+0x5d1): undefined reference to `culibosTlsGetValue'
npp.cpp:(.text+0x5ff): undefined reference to `cudaGetDevice'
npp.cpp:(.text+0x613): undefined reference to `cudaGetDeviceProperties'
npp.cpp:(.text+0x622): undefined reference to `cudaStreamGetFlags'
npp.cpp:(.text+0x68f): undefined reference to `cudaDeviceGetAttribute'
npp.cpp:(.text+0x6b8): undefined reference to `cudaGetDevice'
npp.cpp:(.text+0x6cc): undefined reference to `cudaGetDeviceProperties'
npp.cpp:(.text+0x6df): undefined reference to `cudaStreamGetFlags'
npp.cpp:(.text+0x744): undefined reference to `cudaDeviceGetAttribute'
npp.cpp:(.text+0x763): undefined reference to `cudaDeviceGetAttribute'
npp.cpp:(.text+0x7b3): undefined reference to `cudaDeviceGetAttribute'
/usr/local/cuda/lib64//libnppc.a(npp.o): In function `nppSetStream':
npp.cpp:(.text+0x855): undefined reference to `cudaGetDevice'
npp.cpp:(.text+0x869): undefined reference to `cudaGetDeviceProperties'
npp.cpp:(.text+0x878): undefined reference to `cudaStreamGetFlags'
npp.cpp:(.text+0x8df): undefined reference to `cudaDeviceGetAttribute'
npp.cpp:(.text+0x8fe): undefined reference to `cudaDeviceGetAttribute'
npp.cpp:(.text+0x93e): undefined reference to `culibosTlsSetValue'
npp.cpp:(.text+0x95f): undefined reference to `culibosOnce'
npp.cpp:(.text+0x97b): undefined reference to `cudaGetDevice'
npp.cpp:(.text+0x98f): undefined reference to `cudaGetDeviceProperties'
npp.cpp:(.text+0x99e): undefined reference to `cudaStreamGetFlags'
npp.cpp:(.text+0xa03): undefined reference to `cudaDeviceGetAttribute'
npp.cpp:(.text+0xa1e): undefined reference to `cudaDeviceGetAttribute'
/usr/local/cuda/lib64//libnppc.a(npp.o): In function `nppGetGpuNumSMs':
npp.cpp:(.text+0xa7a): undefined reference to `cudaGetDeviceCount'
/usr/local/cuda/lib64//libnppc.a(npp.o): In function `nppGetMaxThreadsPerBlock':
npp.cpp:(.text+0xaad): undefined reference to `cudaGetDeviceCount'
npp.cpp:(.text+0xaca): undefined reference to `cudaGetDevice'
npp.cpp:(.text+0xada): undefined reference to `cudaGetDeviceProperties'
/usr/local/cuda/lib64//libnppc.a(npp.o): In function `nppGetMaxThreadsPerSM':
npp.cpp:(.text+0xafa): undefined reference to `cudaGetDeviceCount'
/usr/local/cuda/lib64//libnppc.a(npp.o): In function `nppGetGpuDeviceProperties':
npp.cpp:(.text+0xb57): undefined reference to `cudaGetDeviceCount'
npp.cpp:(.text+0xb6f): undefined reference to `cudaGetDevice'
npp.cpp:(.text+0xb7f): undefined reference to `cudaGetDeviceProperties'
/usr/local/cuda/lib64//libnppc.a(npp.o): In function `nppGetGpuName':
npp.cpp:(.text+0xc06): undefined reference to `cudaGetDeviceCount'
npp.cpp:(.text+0xc4d): undefined reference to `cudaGetDevice'
npp.cpp:(.text+0xc5b): undefined reference to `cudaGetDeviceProperties'
/usr/local/cuda/lib64//libnppc.a(npp.o): In function `nppGetPointerMemoryType':
npp.cpp:(.text+0xc7b): undefined reference to `cudaPointerGetAttributes'
npp.cpp:(.text+0xcb1): undefined reference to `cudaGetLastError'
/usr/local/cuda/lib64//libnppc.a(npp.o): In function `nppGetStream':
npp.cpp:(.text+0x2b): undefined reference to `culibosTlsGetValue'
collect2: error: ld returned 1 exit status

**Comment by numberwolf** [comment]
这个应该是ffmpeg编译静态依赖的问题，和flv没什么关系。

然后看你的错误，我看都是cuda 硬编码相关模块的错误，找不到符号表，应该是你的libnpp的版本问题，是enable了什么依赖了吗？

**Comment by WJZMC** [comment]
cuda 的libnpp库的静态库找不到这些，但是动态库可以找到，这个一般怎么搞

**Comment by WJZMC** [comment]
--extra-ldexeflags="-static"  不加这个可以编译通过，加了之后就报了那么多错

**Comment by numberwolf** [comment]
> --extra-ldexeflags="-static" 不加这个可以编译通过，加了之后就报了那么多错

加了这个自动查找静态依赖的，或者看是否可以自己编译静态库，不然的话编译出来你的ffmpeg program需要依赖动态路径查找，不太方便做移植（当然如果你的线上环境全部统一那就没问题，或者把东太依赖都打包进去）

**Comment by WJZMC** [comment]
我查了一下，好像是cuda不支持静态，这个还挺麻烦



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月10日(周三) 晚上11:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [numberwolf/FFmpeg-QuQi-H265-FLV-RTMP] 你定义的flv常量都没用，你试过可以吗？ (#3)




  
--extra-ldexeflags="-static" 不加这个可以编译通过，加了之后就报了那么多错
  
加了这个自动查找静态依赖的，或者看是否可以自己编译静态库，不然的话编译出来你的ffmpeg program需要依赖动态路径查找，不太方便做移植（当然如果你的线上环境全部统一那就没问题，或者把东太依赖都打包进去）

**Comment by numberwolf** [comment]
是吗？  libcuda？  还是libnpp

**Comment by WJZMC** [comment]
libcuda，可以编过去但是用的时候有问题，libnpp. 就编不过去



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月10日(周三) 晚上11:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [numberwolf/FFmpeg-QuQi-H265-FLV-RTMP] 你定义的flv常量都没用，你试过可以吗？ (#3)




 
是吗？  libcuda？  还是libnpp

**Comment by numberwolf** [comment]
> libcuda，可以编过去但是用的时候有问题，libnpp. 就编不过去
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年3月10日(周三) 晚上11:36 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [numberwolf/FFmpeg-QuQi-H265-FLV-RTMP] 你定义的flv常量都没用，你试过可以吗？ (#3) 是吗？ libcuda？ 还是libnpp — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

这个只能用动态的了 一般GPU卡机器不多吧

**Comment by WJZMC** [comment]
那一般常规硬解的流媒体服务器都是用的什么呀



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月11日(周四) 下午2:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [numberwolf/FFmpeg-QuQi-H265-FLV-RTMP] 你定义的flv常量都没用，你试过可以吗？ (#3)




  
libcuda，可以编过去但是用的时候有问题，libnpp. 就编不过去
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2021年3月10日(周三) 晚上11:36 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [numberwolf/FFmpeg-QuQi-H265-FLV-RTMP] 你定义的flv常量都没用，你试过可以吗？ (#3) 是吗？ libcuda？ 还是libnpp — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
这个只能用动态的了 一般GPU卡机器不多吧

**Comment by numberwolf** [comment]
> 那一般常规硬解的流媒体服务器都是用的什么呀
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年3月11日(周四) 下午2:20 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [numberwolf/FFmpeg-QuQi-H265-FLV-RTMP] 你定义的flv常量都没用，你试过可以吗？ (#3) libcuda，可以编过去但是用的时候有问题，libnpp. 就编不过去 … ---原始邮件--- 发件人: @.&gt; 发送时间: 2021年3月10日(周三) 晚上11:36 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [numberwolf/FFmpeg-QuQi-H265-FLV-RTMP] 你定义的flv常量都没用，你试过可以吗？ (#3) 是吗？ libcuda？ 还是libnpp — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 这个只能用动态的了 一般GPU卡机器不多吧 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

硬解码的方式就有很多了 解码不会消耗多少时间的，软解也没多少时间，主要时间在编码上；
