### ISSUE TITLE
error:Unknown encoder 'libx265'

### ISSUE THREAD

**Issue by Gandalf8266** [numberwolf/FFmpeg-QuQi-H265-FLV-RTMP#6]
I compiled and installed the FFmpeg-QuQi-H265-FLV-RTMP.
I tried to stream my IP-cam to my YouTube Channel with this command:

ffmpeg -re -i rtsp://User:passwort@CAM-IP:554/live/ch00_1 -vcodec libx265 -acodec aac -f flv rtmp://a.rtmp.youtube.com/live2/myStreamKey

It don't work, I got that message: 
Unknown encoder 'libx265'

the rtsp Stream works with vlc Player on the same Raspberry Pi
here is a screenshot of the messages:
![ffmpeg](https://user-images.githubusercontent.com/38372908/118594426-be993600-b7a9-11eb-986d-c2bd56f55d36.png)

**Comment by numberwolf** [comment]
Here: 
See this issue: https://github.com/numberwolf/FFmpeg-QuQi-H265-FLV-RTMP/issues/4

> Hey ,
> Your enviorment missing libx265.
> 
> You need to install libx265(encoder) on your machine.
> 
> MacOS:
> brew install x265
> 
> Centos:
> yum install x265
> 
> Ubuntu:
> apt-get install x265

**Comment by Gandalf8266** [comment]
I tried on my raspberry Pi:
_sudo install apt-get install x265_

The result was:
install: target 'x265' is not a directory

**Comment by numberwolf** [comment]
do you have picture?

1)you need to input :
```
apt-cache search x265
```

give me your result

**Comment by Gandalf8266** [comment]
that's my result:
pi@osb:~ $ apt-cache search x265
libx265-165 - H.265/HEVC video stream encoder (shared library)
libx265-dev - H.265/HEVC video stream encoder (development files)
libx265-doc - H.265/HEVC video stream encoder (documentation)
x265 - H.265/HEVC video stream encoder

**Comment by numberwolf** [comment]
execute:
```
apt-get install libx265-dev
apt-get install x265
```

**Comment by numberwolf** [comment]
then
re compile ffmpeg

**Comment by Gandalf8266** [comment]
I did as you described, but I have still the same Problem...

**Comment by numberwolf** [comment]
> I did as you described, but I have still the same Problem...

How do you compile your ffmpeg?  whats your compile's configure content?

**Comment by numberwolf** [comment]
I think you compile not right.  you havent compile x265 into ffmpeg.

Base on you have install x265 dev on your machine.

**Comment by Gandalf8266** [comment]
I think there is another Problem, I tried to use a HIKAM S6 3.Gen to stream with ffpmeg, I enabled rtsp Protokoll, the stream works with VLC Player. 
I tried to use the stream is OBS Studio, but the screen remains black.

I also tried an other IP CAM Model V 380, with this one, screen in OBS Studio shows the video stream.
I'm also able to stream the V 380 camera to my YouTube Stream with following command:
ffmpeg -f lavfi -i anullsrc -rtsp_transport udp -i rtsp://_USER_:_PW_@_myIP_:554/live/ch00_1 -vcodec libx264 -t 12:00:00 -pix_fmt + -c:v copy -c:a aac -strict experimental -f flv rtmp://a.rtmp.youtube.com/live2/_streamkey_

aktually I don't know, why the HIKAM won't work in OBS Studio 
![osb](https://user-images.githubusercontent.com/38372908/118646625-ba3c3f80-b7e0-11eb-9379-95b28e7f227b.png)

**Comment by numberwolf** [comment]
> eg -f lavfi -i anullsrc -rtsp_transport udp -i rtsp://_USER_:_PW_@_myIP_:554/live/ch00_1 -vcodec libx264 -t 12:00:00 -pix_fmt + -c:v copy -c:a aac -strict experimental -f flv rtmp://a.rtmp.youtube.com/live2/_streamkey_

This is libx264.. not H.265

you input: `ffmpeg -encoders | grep 265` to check your x265 is or not in ffmpeg.

**Comment by numberwolf** [comment]
Right configure:
#!/bin/bash
./configure \
  --enable-cross-compile \
  --pkg-config-flags="--static" \
  --extra-ldflags="-lm -lz -llzma -lpthread" \
  --extra-libs=-lpthread \
  --extra-libs=-lm \
  --enable-gpl \
  --enable-libfdk_aac \
  --enable-libfreetype \
  --enable-libmp3lame \
  --enable-libx264 \
  --enable-libx265 \
  --enable-libass \
  --enable-libfreetype       \
  --enable-libfontconfig     \
  --enable-libfribidi        \
  --enable-nonfree \
  --disable-shared \
  --enable-static
make clean
make -j16
make install

**Comment by numberwolf** [comment]
> --enable-libx265

this option will compile your ffmpeg with x265 encoder

**Comment by Gandalf8266** [comment]
I know, that was libx264, the V380 cam ist not a h265 one.

do I have to run the ./configure with that parameters?

**Comment by numberwolf** [comment]
Hey , brother..

Have a look about your issue title: `unknow encoder libx265`

This error message, means you havent add `--enable-libx265` to your configure params.

And this ffmpeg library's top feature is : support HEVC for rtmp/flv. 

So if you do not compile with x265, you can not push rtmp/flv live stream with codec named HEVC(H.265).
